server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: password
  rabbitmq:
    username: admin
    password: 123
    host: 192.168.209.130
    port: 5672
#    消息确认回调
    publisher-confirm-type: correlated
#    消息失败回调
    publisher-returns: true
  #    druid:
#      min-idle: 5
  redis:
#    超时时间
    timeout: 10000ms
    host: 192.168.209.130
    port: 6379
    database: 0
    password: password
    jedis:
      pool:
#        最大连接数
        max-active: 1024
#        最大等待时间
        max-wait: 10000ms
#        最大空闲连接
        max-idle: 200
#        最小空闲连接
        min-idle: 5


mybatis-plus:
#  配置文件位置
  mapper-locations: classpath*:mapper/*.xml
#  配置别名
  type-aliases-package: com.study.server.pojo
  configuration:
#    关闭自动驼峰命名
    map-underscore-to-camel-case: false
logging:
  level:
    com.study.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
#  expiration: 1
  tokenHead: Bearer